export const apiEndpoints = {
  login: 'auth/login',
  register: 'auth/register',
  getCategories: 'categories',
  getBooks: 'books',
  getRecommendedBooks: 'books/recommended',
  getBookDetail: 'books/:id',
  updateBookDetail: 'books/:id',
  deleteBook: 'books/:id',
  getAuthor: 'authors',
  getBookReview: 'reviews/book/:id',
  getBookByAuthor: 'authors/:id/books',
  getProfile: 'me',
  getLoanBooks: 'me/loans',
  postLoanBook: 'loans',
  getMyLoansBooks: 'loans/my',
  // getUser: 'users/:id',
  // getUsers: 'users',
  // getUserBooks: 'users/:id/books',
  // getUserBook: 'users/:id/books/:bookId',
  // getUserCategories: 'users/:id/categories',
  // getUserCategory: 'users/:id/categories/:categoryId',
};
